[build]
  base = "/"
  command = "npm start"
  publish = "/mainApp/"
  functions = "functions/"
  [build.environment]
    NODE_VERSION = "18"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  to = "/main.html"
  status = 200